package com.elmansoft.elmancall.ui.login

data class UserInfoDTO (
    var custcd: String,
    var spjangcd: String,
    var perid: String,
    var kukcd: String,
    var pernm: String,
    var divicd: String,
    var divinm: String,
    var rspnm: String,
    var spjangnm: String,
    var tel: String,
    var tel2: String,
    var spjangcd_lat: String,
    var spjangcd_lng: String,
    var weather: String,
    var chk: String,
    var noticeflag: String,
    var totusers: String,
    var userid: String,
    var handphone: String,
    var quality: String,
    var lat: String,
    var lng: String,
    var commute: String,
    var call_type: String,
    var pushtye: String,
    var emailadres: String,
    var groupid: String,
    var grouppw: String,
    var theme: String,
    var contflag: String,
    var contrast: String,
    var gpsAgreeStdate: String,
    var gpsAgreeEddate: String,
    var gpsAgreeIndate: String,
    var gpsAgreeIntime: String,
)
